version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
     - ./data/init-scripts:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER:-root}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASS:-root}'
      MONGO_INITDB_DATABASE: '${DB_NAME:-mind_crud}'
  backend:
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./data/uploads:/app/uploads
    environment:
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET:-access_token}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET:-refresh_token}"
      MONGODB_DATABASE: '${DB_NAME:-mind_crud}'
      MONGODB_USER: '${DB_USER:-root}'
      MONGODB_PASSWORD: '${DB_PASS:-root}'
      MONGODB_HOST: '${DB_HOST:-mongodb}'
      DEBUG: 'true'
    restart: always
  frontend:
    build: ./frontend
    depends_on:
      - mongodb
    ports:
      - 8080:3000
    restart: always
